#!/bin/sh

set -e

# Load environmental variables if exists.
[ -f /etc/default/hello ] && . /etc/default/hello

#----------------------------------------------------

echo "Running postinst script:" $@

chmod 755 /usr/bin/hello

if [ ! -d /var/lib/hello/ ]; then
    mkdir /var/lib/hello/
    chmod 644 /var/lib/hello/
fi

#----------------------------------------------------
exit 0
