#!/bin/sh

set -e

# Load environmental variables if exists.
[ -f /etc/default/hello ] && . /etc/default/hello

#----------------------------------------------------

echo "Running prerm script:" $@

#----------------------------------------------------
exit 0
