name: Go Vet

on:
  workflow_dispatch:
    inputs:
      args:
        description: ""
        required: false
        type: string
        default: ""
  workflow_call:
    inputs:
      go-version:
        description: "go-version for setup-go job"
        required: false
        type: string
        default: "stable"
      go-version-file:
        description: "go-version-file for setup-go job"
        required: false
        type: string
        default: ""
      check-latest:
        description: "check-latest for setup-go job"
        required: false
        type: boolean
        default: 'true'
      args:
        description: "additional args for make go-vet"
        required: false
        type: string
        default: ""
  push:
    branches: ["**"]

permissions:
  contents: read 

jobs:
  vet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          go-version-file: ${{ inputs.go-version-file }}
          check-latest: ${{ inputs.check-latest }}
          cache: false
      - run: make go-vet ARGS="${{ inputs.args }}"
