name: Go Vet

on:
  workflow_dispatch:
    inputs:
      args:
        description: ""
        required: false
        type: string
        default: ""
  workflow_call:
    inputs:
      args:
        description: ""
        required: false
        type: string
        default: ""
  push:
    branches: ["**"]

jobs:
  vet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: make go-vet ARGS="${{ inputs.args }}"
